/**
 * Service worker registration for the installable PWA shell.
 *
 * Registration is production-only: dev servers and tests never install a
 * worker, so local development and Vitest stay service-worker-free. The
 * worker is generated by vite-plugin-pwa with `registerType: 'autoUpdate'`:
 * a fresh deploy activates in the background and, once it takes control,
 * the open page reloads once so a running session never mixes old markup
 * with new hashed chunks. Progress is local-first and pending notes flush
 * on pagehide, so the reload loses nothing.
 *
 * Registration is deferred until the window load event has fired and the
 * main thread goes idle: the first install precaches the whole app shell
 * (~2.5 MiB), which would otherwise compete with the style, glyph and tile
 * fetches the first map render needs on slow connections.
 */

export interface ServiceWorkerEnvironment {
  isProduction: boolean;
  supportsServiceWorker: boolean;
  /** True inside the Capacitor WebView, where assets are already on disk. */
  isNativeWrapper: boolean;
}

type RegisterSwModule = typeof import('virtual:pwa-register');

export function detectServiceWorkerEnvironment(): ServiceWorkerEnvironment {
  return {
    isProduction: import.meta.env.PROD,
    supportsServiceWorker:
      typeof navigator !== 'undefined' && 'serviceWorker' in navigator,
    // Capacitor injects a `Capacitor` global into its WebView. The wrapped
    // app serves everything from the app bundle, so a service worker would
    // only re-cache files that are already local — skip it.
    isNativeWrapper: typeof window !== 'undefined' && 'Capacitor' in window,
  };
}

export function shouldRegisterServiceWorker(
  environment: ServiceWorkerEnvironment,
): boolean {
  return (
    environment.isProduction &&
    environment.supportsServiceWorker &&
    !environment.isNativeWrapper
  );
}

/**
 * Runs `callback` after the load event once the main thread goes idle,
 * keeping the precache download out of the critical first-render window.
 */
function scheduleWhenIdleAfterLoad(callback: () => void): void {
  const scheduleIdle = () => {
    if (typeof window.requestIdleCallback === 'function') {
      // The timeout caps the wait so offline support still arrives on pages
      // that never go idle (e.g. continuous map animation).
      window.requestIdleCallback(
        () => {
          callback();
        },
        { timeout: 10_000 },
      );
    } else {
      window.setTimeout(callback, 3_000);
    }
  };

  if (document.readyState === 'complete') {
    scheduleIdle();
  } else {
    window.addEventListener('load', scheduleIdle, { once: true });
  }
}

export function registerServiceWorker(
  environment: ServiceWorkerEnvironment = detectServiceWorkerEnvironment(),
  loadRegisterModule: () => Promise<RegisterSwModule> = () =>
    import('virtual:pwa-register'),
  schedule: (callback: () => void) => void = scheduleWhenIdleAfterLoad,
): boolean {
  if (!shouldRegisterServiceWorker(environment)) {
    return false;
  }

  schedule(() => {
    loadRegisterModule()
      .then(({ registerSW }) => {
        registerSW({ immediate: true });
      })
      .catch((error: unknown) => {
        // A failed registration only costs offline support; the app still
        // runs.
        console.error('Munro service worker registration failed.', error);
      });
  });

  return true;
}
