/**
 * Service worker registration for the installable PWA shell.
 *
 * Registration is production-only: dev servers and tests never install a
 * worker, so local development and Vitest stay service-worker-free. The
 * worker is generated by vite-plugin-pwa with `registerType: 'autoUpdate'`,
 * which keeps updates unobtrusive — a new shell activates in the background
 * and is served on the next visit, with no refresh prompts.
 */

export interface ServiceWorkerEnvironment {
  isProduction: boolean;
  supportsServiceWorker: boolean;
  /** True inside the Capacitor WebView, where assets are already on disk. */
  isNativeWrapper: boolean;
}

type RegisterSwModule = typeof import('virtual:pwa-register');

export function detectServiceWorkerEnvironment(): ServiceWorkerEnvironment {
  return {
    isProduction: import.meta.env.PROD,
    supportsServiceWorker:
      typeof navigator !== 'undefined' && 'serviceWorker' in navigator,
    // Capacitor injects a `Capacitor` global into its WebView. The wrapped
    // app serves everything from the app bundle, so a service worker would
    // only re-cache files that are already local — skip it.
    isNativeWrapper: typeof window !== 'undefined' && 'Capacitor' in window,
  };
}

export function shouldRegisterServiceWorker(
  environment: ServiceWorkerEnvironment,
): boolean {
  return (
    environment.isProduction &&
    environment.supportsServiceWorker &&
    !environment.isNativeWrapper
  );
}

export function registerServiceWorker(
  environment: ServiceWorkerEnvironment = detectServiceWorkerEnvironment(),
  loadRegisterModule: () => Promise<RegisterSwModule> = () =>
    import('virtual:pwa-register'),
): boolean {
  if (!shouldRegisterServiceWorker(environment)) {
    return false;
  }

  loadRegisterModule()
    .then(({ registerSW }) => {
      registerSW({ immediate: true });
    })
    .catch((error: unknown) => {
      // A failed registration only costs offline support; the app still runs.
      console.error('Munro service worker registration failed.', error);
    });

  return true;
}
